-- ============================================================================
-- Migration 011: Order Execution Log Table
--
-- Purpose: Detailed log of all order executions with timing, fills, slippage
-- Supports: Multi-leg orders (synthetic futures), partial fills, retries
-- Retention: 90 days
--
-- Author: Claude Code
-- Date: January 2026
-- ============================================================================

-- Drop table if exists (for clean re-runs during development)
-- REMOVE THIS LINE BEFORE PRODUCTION USE
-- DROP TABLE IF EXISTS order_execution_log CASCADE;

CREATE TABLE IF NOT EXISTS order_execution_log (
    id BIGSERIAL PRIMARY KEY,

    -- ========================================================================
    -- Links to related records
    -- ========================================================================

    -- Link to signal_audit (which signal triggered this order)
    signal_audit_id BIGINT REFERENCES signal_audit(id) ON DELETE SET NULL,

    -- Link to portfolio_positions (which position this affects)
    position_id VARCHAR(50),

    -- ========================================================================
    -- Order Identification
    -- ========================================================================

    -- Internal order ID (generated by PM)
    order_id VARCHAR(100),

    -- Broker's order ID (from OpenAlgo/Zerodha)
    broker_order_id VARCHAR(100),

    -- ========================================================================
    -- Order Details
    -- ========================================================================

    -- Order type
    order_type VARCHAR(30) NOT NULL,
    -- Valid types:
    --   SYNTHETIC_FUTURES  - ATM CE Buy + PE Sell (Bank Nifty)
    --   DIRECT_FUTURES     - Direct futures order (Gold/Silver Mini)
    --   OPTION_BUY         - Single option buy
    --   OPTION_SELL        - Single option sell

    -- Action
    action VARCHAR(10) NOT NULL,  -- BUY, SELL

    -- Instrument details
    instrument VARCHAR(20) NOT NULL,    -- BANK_NIFTY, GOLD_MINI, etc.
    symbol VARCHAR(100) NOT NULL,       -- Full trading symbol
    exchange VARCHAR(20) NOT NULL,      -- NFO, MCX, NSE

    -- Quantity
    quantity INTEGER NOT NULL,          -- Total quantity (lots * lot_size)
    lots INTEGER NOT NULL,              -- Number of lots

    -- ========================================================================
    -- Pricing & Slippage
    -- ========================================================================

    -- Signal price (from TradingView)
    signal_price DECIMAL(12,2),

    -- Limit price (what we sent to broker)
    limit_price DECIMAL(12,2),

    -- Actual fill price
    fill_price DECIMAL(12,2),

    -- Slippage percentage: ((fill - signal) / signal) * 100
    slippage_pct DECIMAL(6,4),

    -- ========================================================================
    -- Status & Messaging
    -- ========================================================================

    -- Order status
    order_status VARCHAR(20) NOT NULL,
    -- Valid statuses:
    --   PENDING     - Order submitted, awaiting response
    --   OPEN        - Order accepted, not yet filled
    --   COMPLETE    - Order fully filled
    --   PARTIAL     - Order partially filled
    --   REJECTED    - Order rejected by broker
    --   CANCELLED   - Order cancelled
    --   FAILED      - Order placement failed (network, etc.)

    -- Status message (reason for rejection, etc.)
    status_message TEXT,

    -- ========================================================================
    -- Timing
    -- ========================================================================

    -- When order was placed
    order_placed_at TIMESTAMP,

    -- When order was filled (or last fill for partial)
    order_filled_at TIMESTAMP,

    -- Total execution duration in milliseconds
    execution_duration_ms INTEGER,

    -- ========================================================================
    -- Multi-Leg Order Support
    -- ========================================================================

    -- For synthetic futures, links legs together
    -- Parent order ID (self-reference for multi-leg orders)
    parent_order_id BIGINT REFERENCES order_execution_log(id) ON DELETE SET NULL,

    -- Leg number (1 = CE leg, 2 = PE leg for synthetic futures)
    leg_number INTEGER,

    -- ========================================================================
    -- Raw Data
    -- ========================================================================

    -- Full broker response (for debugging)
    raw_response JSONB,

    -- ========================================================================
    -- Timestamps
    -- ========================================================================

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    -- ========================================================================
    -- Constraints
    -- ========================================================================

    -- Validate order_type values
    CONSTRAINT chk_order_exec_type CHECK (
        order_type IN (
            'SYNTHETIC_FUTURES',
            'DIRECT_FUTURES',
            'OPTION_BUY',
            'OPTION_SELL',
            'MARKET',
            'LIMIT'
        )
    ),

    -- Validate action values
    CONSTRAINT chk_order_exec_action CHECK (
        action IN ('BUY', 'SELL')
    ),

    -- Validate order_status values
    CONSTRAINT chk_order_exec_status CHECK (
        order_status IN (
            'PENDING',
            'OPEN',
            'COMPLETE',
            'PARTIAL',
            'REJECTED',
            'CANCELLED',
            'FAILED'
        )
    ),

    -- Validate exchange values
    CONSTRAINT chk_order_exec_exchange CHECK (
        exchange IN ('NFO', 'MCX', 'NSE', 'BSE', 'BFO')
    ),

    -- Validate leg_number (1-4 for multi-leg orders)
    CONSTRAINT chk_order_exec_leg CHECK (
        leg_number IS NULL OR (leg_number >= 1 AND leg_number <= 4)
    )
);

-- ============================================================================
-- Indexes for common query patterns
-- ============================================================================

-- Query orders by signal audit
CREATE INDEX IF NOT EXISTS idx_order_exec_signal
    ON order_execution_log(signal_audit_id);

-- Query orders by position
CREATE INDEX IF NOT EXISTS idx_order_exec_position
    ON order_execution_log(position_id);

-- Query orders by status (find failed orders)
CREATE INDEX IF NOT EXISTS idx_order_exec_status
    ON order_execution_log(order_status);

-- Query orders by time (for Telegram bot /orders command)
CREATE INDEX IF NOT EXISTS idx_order_exec_time
    ON order_execution_log(order_placed_at DESC);

-- Query orders by broker order ID (for fill updates)
CREATE INDEX IF NOT EXISTS idx_order_exec_broker_id
    ON order_execution_log(broker_order_id);

-- Query multi-leg orders
CREATE INDEX IF NOT EXISTS idx_order_exec_parent
    ON order_execution_log(parent_order_id)
    WHERE parent_order_id IS NOT NULL;

-- Combined index for dashboard queries
CREATE INDEX IF NOT EXISTS idx_order_exec_instrument_status
    ON order_execution_log(instrument, order_status, order_placed_at DESC);

-- ============================================================================
-- Trigger for updated_at
-- ============================================================================

CREATE OR REPLACE FUNCTION update_order_execution_log_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_order_execution_log_updated ON order_execution_log;
CREATE TRIGGER trg_order_execution_log_updated
    BEFORE UPDATE ON order_execution_log
    FOR EACH ROW
    EXECUTE FUNCTION update_order_execution_log_timestamp();

-- ============================================================================
-- Comments for documentation
-- ============================================================================

COMMENT ON TABLE order_execution_log IS 'Detailed log of all order executions with timing, fills, and slippage. 90-day retention.';
COMMENT ON COLUMN order_execution_log.order_type IS 'Order type: SYNTHETIC_FUTURES, DIRECT_FUTURES, OPTION_BUY, OPTION_SELL';
COMMENT ON COLUMN order_execution_log.slippage_pct IS 'Slippage as percentage: ((fill_price - signal_price) / signal_price) * 100';
COMMENT ON COLUMN order_execution_log.parent_order_id IS 'For multi-leg orders, links child legs to parent order';
COMMENT ON COLUMN order_execution_log.leg_number IS 'Leg number for multi-leg orders: 1=CE, 2=PE for synthetic futures';

-- ============================================================================
-- Verification query (run after migration)
-- ============================================================================
-- SELECT
--     table_name,
--     column_name,
--     data_type,
--     is_nullable
-- FROM information_schema.columns
-- WHERE table_name = 'order_execution_log'
-- ORDER BY ordinal_position;
